name: envy
description: An information visualization framework.
version: 0.4.1
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: '>=2.8.4 <3.0.0'
dependencies:
  angular: ^6.0.0-alpha
  collection: ^1.14.0
  quantity: ^1.0.0
  logging: ^0.11.4
  vector_math: ^2.0.5
dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.5.0
  build_test: ^0.10.1+1
  build_web_compilers: ^2.0.0
  pedantic: ^1.9.0
  test: ^1.3.0
