name: envy
description: An information visualization framework.
version: 0.3.0
author: Rob Bishop <@robbishop65@gmail.com>
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  collection: ^1.14.0
  quantity: ^0.2.0+1
  vector_math: ^2.0.5
dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.0
  build_test: ^0.10.1+1
  build_web_compilers: ^1.0.0
  test: ^1.3.0
