name: envy
description: An information visualization framework.
version: 0.5.0
homepage: https://github.com/cooler-king/envy
documentation: https://github.com/cooler-king/envy/wiki
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  #angular: ^6.0.0
  collection: ^1.14.0
  logging: ^1.0.0
  quantity: ^2.0.0
  vector_math: ^2.1.0
dev_dependencies:
  #angular_test: ^3.0.0
  #build_runner: ^1.5.0
  #build_test: ^1.0.0
  #build_web_compilers: ^2.0.0
  #flutter_lints: ^1.0.4
  #pedantic: ^1.9.0
  test: ^1.15.0
